@isTest
private class GoogleAnalyticsImporter_Test {
	/*
	static testMethod void testShceduledJob()
   {
   	    AnalyticSettingsController asController = new AnalyticSettingsController();

        //Temporarily save a site info for testing
        String siteName = 'MyBlog';
        asController.settings = new Site_Metric_Settings__c(Name = siteName, Email__c = 'as@as.com', Password__c = '123', Table_Id__c = 'ga:123456');
        PageReference returnedPageRef = asController.save();
        asController.settings = null;
   	
       Test.startTest();
       GoogleAnalyticsImporter gai = new GoogleAnalyticsImporter();
        Datetime dt = Datetime.now().addMinutes(1);
        String sch = '0 '+dt.minute()+' * '+dt.day()+' '+dt.month()+' '+' ? '+dt.year();
        
       System.schedule('Schedule', sch, gai);
       test.stoptest();
   }
   */
}